# Generated by Django 4.1.7 on 2023-02-16 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bikesantiago_empty_slots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikesantiago',
            old_name='station',
            new_name='name_station',
        ),
    ]
