# Generated by Django 4.1.7 on 2023-02-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_station_bikesantiago_name_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikesantiago',
            old_name='empty_slots',
            new_name='free_bikes',
        ),
        migrations.RemoveField(
            model_name='bikesantiago',
            name='total_attendance',
        ),
        migrations.AddField(
            model_name='bikesantiago',
            name='id_station',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bikesantiago',
            name='name_station',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
