# Generated by Django 4.1.7 on 2023-02-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_empty_slots_bikesantiago_free_bikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikesantiago',
            name='free_bikes',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
