# Generated by Django 4.1.7 on 2023-02-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bikesantiago_free_bikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_station', models.CharField(max_length=200, unique=True)),
                ('name_station', models.CharField(max_length=200, null=True)),
                ('free_bikes', models.CharField(max_length=200, null=True)),
                ('empty_slots', models.CharField(max_length=200, null=True)),
                ('date', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('ebikes', models.CharField(blank=True, max_length=200, null=True)),
                ('has_ebikes', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BikeSantiago',
        ),
    ]
