# Generated by Django 4.1.7 on 2023-02-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bikes_delete_bikesantiago'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='normal_bikes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
