# Generated by Django 4.1.7 on 2023-02-17 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bikes_normal_bikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('bicicletas_disponibles', models.IntegerField()),
                ('espacios_disponibles', models.IntegerField()),
                ('ultima_actualizacion', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Bikes',
        ),
    ]
