# Generated by Django 4.1.7 on 2023-02-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_estacion_delete_bikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No', models.IntegerField()),
                ('Nombre', models.CharField(max_length=255)),
                ('Tipo', models.CharField(max_length=10)),
                ('Región', models.CharField(max_length=20)),
                ('Tipología', models.CharField(max_length=5)),
                ('Titular', models.CharField(max_length=255)),
                ('Inversión', models.DecimalField(decimal_places=4, max_digits=10)),
                ('FechaPresentaciónFecha', models.DateField()),
                ('Estado', models.CharField(max_length=30)),
                ('Mapa', models.CharField(max_length=255)),
            ],
        ),
    ]
